begin;
select plan(18);
select has_table('public', 'cities', 'cities existe');
select has_table('public', 'request_cities', 'request_cities existe');
select has_column('public', 'user_permissions', 'can_manage_cities', 'permissão de cidades existe');
select has_function('public', 'has_city_management_permission', array[]::text[], 'função de permissão existe');
select has_function('public', 'create_city', array['text'], 'create_city existe');
select has_function('public', 'rename_city', array['uuid','text'], 'rename_city existe');
select has_function('public', 'deactivate_city', array['uuid'], 'deactivate_city existe');
select has_function('public', 'reactivate_city', array['uuid'], 'reactivate_city existe');
select has_function('public', 'create_request_with_cities', array['text','text','uuid','text','numeric','text[]','uuid[]'], 'RPC de criação com cidades existe');
select has_function('public', 'update_request_with_cities', array['uuid','text','text','uuid','text','text[]','uuid[]'], 'RPC de edição com cidades existe');
select col_is_pk('public', 'request_cities', array['request_id','city_id'], 'vínculo não duplica');
select ok((select count(*) from public.request_cities) = (select count(*) from public.requests), 'backfill associa cada solicitação legada');
select ok(not has_table_privilege('authenticated', 'public.cities', 'insert'), 'cliente não insere cidades diretamente');
select ok(not has_table_privilege('authenticated', 'public.request_cities', 'insert'), 'cliente não insere vínculos diretamente');
select function_privs_are('public', 'create_city', array['text'], 'authenticated', array['EXECUTE'], 'autenticado chama create_city');
select function_privs_are('public', 'create_city', array['text'], 'public', array[]::text[], 'público não chama create_city');
select ok(has_table_privilege('authenticated', 'public.cities', 'select'), 'aprovados podem ler cidades via RLS');
select ok(has_table_privilege('authenticated', 'public.request_cities', 'select'), 'aprovados podem ler vínculos via RLS');
select * from finish();
rollback;
